### ISSUE TITLE
Using address bar

### ISSUE THREAD

**Issue by gdbaldw** [andreasbm/router-slot#3]
All works for me so far including routing to a LitElement in a separate file. But, typing a valid route at the address bar results in page reload and a "Not Found" page. Not sure if this behavior is avoidable. Is this expected behavior, and if so is there a plan or approach for using the address bar with router-slot?

**Comment by gdbaldw** [comment]
Seems that catching [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) and modifying history is an approach

**Comment by andreasbm** [comment]
Thanks for opening this issue! 👍In order to investigate your issue I'm going to need you to provide some more information and if possible a code example. Your issue sounds like something that would occur if the server you are using doesn't redirects all requests to `index.html` - you are therefore very welcome to check if that is the case 🌞

**Comment by gdbaldw** [comment]
Yes, I'd researched further and found it a common issue for routers on a single page app, not particular to your router. Workarounds include coordination with the app server, as your comment suggests.
